const fs = require('fs');

const MAX_DAYS = 14;
const MAX_ITEMS_PER_DAY = 20;

let output = `; Generated by gen_meters.js\n`;
output += `; All Y-Positioning is handled by SonarrParse.lua to prevent Hidden meter bugs.\n\n`;

for (let d = 1; d <= MAX_DAYS; d++) {
    const dayGroup = `Day${d}`;

    // --- Day Header ---
    output += `[MeterDay${d}Header]\n`;
    output += `Meter=String\n`;
    output += `MeterStyle=StyleDateHeader\n`;
    output += `Group=${dayGroup}\n`;
    output += `Hidden=1\n`;
    output += `DynamicVariables=1\n\n`;

    for (let i = 1; i <= MAX_ITEMS_PER_DAY; i++) {
        const itemGroup = `Day${d}Item${i}`;
        const prefix = `Day${d}Item${i}`;

        // 1. HITBOX
        output += `[${prefix}Hitbox]\n`;
        output += `Meter=Image\n`;
        output += `MeterStyle=StyleHitbox\n`;
        output += `Group=${dayGroup}|${itemGroup}\n`;
        output += `Hidden=1\n`;
        output += `DynamicVariables=1\n\n`;

        // 2. HIGHLIGHT
        output += `[${prefix}Highlight]\n`;
        output += `Meter=Shape\n`;
        output += `MeterStyle=StyleHighlightShape\n`;
        output += `Group=${dayGroup}|${itemGroup}\n`;
        output += `Hidden=1\n`;
        output += `DynamicVariables=1\n\n`;

        // 3. DOT
        output += `[${prefix}Dot]\n`;
        output += `Meter=Shape\n`;
        output += `MeterStyle=StyleStatusDot\n`;
        output += `Group=${dayGroup}|${itemGroup}\n`;
        output += `Hidden=1\n`;
        output += `DynamicVariables=1\n\n`;

        // 4. TITLE
        output += `[${prefix}Title]\n`;
        output += `Meter=String\n`;
        output += `MeterStyle=StyleShowTitle\n`;
        output += `Group=${dayGroup}|${itemGroup}\n`; // No spaces!
        output += `Text=Init\n`;             // Default text ensures height > 0
        output += `Hidden=1\n`;
        output += `DynamicVariables=1\n\n`;

        // 5. EPISODE INFO
        output += `[${prefix}Episode]\n`;
        output += `Meter=String\n`;
        output += `MeterStyle=StyleEpisodeInfo\n`;
        output += `Group=${dayGroup}|${itemGroup}\n`;
        output += `Text=Init\n`;
        output += `Hidden=1\n`;
        output += `DynamicVariables=1\n\n`;

        // 6. TIME
        output += `[${prefix}Time]\n`;
        output += `Meter=String\n`;
        output += `MeterStyle=StyleTime\n`;
        output += `Group=${dayGroup}|${itemGroup}\n`;
        output += `Text=Init\n`;
        output += `Hidden=1\n`;
        output += `DynamicVariables=1\n\n`;
    }

    // --- Overflow Text ---
    output += `[MeterDay${d}Overflow]\n`;
    output += `Meter=String\n`;
    output += `MeterStyle=StyleOverflow\n`;
    output += `Group=${dayGroup}\n`;
    output += `Hidden=1\n`;
    output += `DynamicVariables=1\n\n`;
}

fs.writeFileSync('gen_meters.inc', output);
console.log(`Generated skin (Logic Moved to Lua).`);